# Generated by Django 4.2.6 on 2023-10-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservacion', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('practica_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.practicasalumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Sessiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('reservacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessiones.reservaciones')),
            ],
        ),
    ]
