# Generated by Django 4.2.6 on 2023-10-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
        ('sessiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='practica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.practicas'),
        ),
    ]
