# Generated by Django 4.2.6 on 2023-10-30 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
        ('sessiones', '0002_alter_reservaciones_practica_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='fecha_reservacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='practica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.practicasalumnos'),
        ),
    ]
