# Generated by Django 4.2.6 on 2023-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessiones', '0007_reservaciones_reagendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='fecha_reservacion',
            field=models.DateTimeField(),
        ),
    ]
