# Generated by Django 4.2.6 on 2023-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_is_staff_alter_usuarios_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Registro_Semestre',
        ),
    ]
