# Generated by Django 4.2.6 on 2023-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_registro_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AlterField(
            model_name='registro_semestre',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo Universitario'),
        ),
        migrations.AddField(
            model_name='role',
            name='Role',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
