# Generated by Django 4.2.6 on 2023-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupos_alumnos_alter_grupos_maestro_id'),
        ('usuarios', '0006_remove_role_role_alter_registro_semestre_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='grupos',
            field=models.ManyToManyField(to='grupos.grupos'),
        ),
    ]
