# Generated by Django 4.2.6 on 2023-10-23 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='maestro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
