# Generated by Django 4.2.6 on 2023-11-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupos_alumnos_alter_grupos_maestro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
