# Generated by Django 4.2.6 on 2023-11-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_alter_grupos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
